### ISSUE TITLE
Не проходят тесты на статус "APPROVED" при подключении к базе данных PostgreSQL

### ISSUE THREAD

**Issue by Olelucoe** [Olelucoe/Diplom_QA#18]
### Описание
При подключении к БД PostgreSQL тесты на статус APPROVED по номеру 4444 4444 4444 4441(дебет и кредит) НЕ проходят.

**Шаги**
1. Ввести в терминале команду docker-compose up
2. Ввести в терминале команду  java "-Dspring.datasource.url=jdbc:postgresql://localhost:5432/app" -jar artifacts/aqa-shop.jar
3. Запустить тест **shouldBuyAllFieldValidApprovedCard()**
![тест, который не работает с постгрес](https://user-images.githubusercontent.com/106590777/208628958-ed782378-f3c2-494d-abbd-efbbc6b6e46c.JPG)

**Результат:**
![postgres ошибка](https://user-images.githubusercontent.com/106590777/208629133-f2182402-d713-45c1-9a1a-6c42908fa224.JPG)

Пишет, что таблица 'app.payment_entity' не существует.

То же самое с тестом **shouldPurchaseCreditAllFieldValidApprovedCard()**
![image](https://user-images.githubusercontent.com/106590777/208632551-e2b1de77-6a14-481f-8c77-b3131545e204.png)

При подключении же к **БД MySQL** оба этих теста работают.

На всякий случай прилагаю настройки build.gradle(это уже изменённый вариант - ещё не запушил на Гитхаб):
![билд_гредл](https://user-images.githubusercontent.com/106590777/208629714-63036d4f-95f4-4dd1-bd1d-d4be1b99c1e2.JPG)

P.S: Пробовал в [SqlHelper](https://github.com/Olelucoe/Diplom_QA/blob/main/src/test/java/Data/SQLHelper.java) ставить app. перед sql-запросом SELECT status FROM payment_entity - не помогло.
Что я делаю не так?

**Comment by andrew-pahomov** [comment]
Рекомендую Вам при запуске тестов выполнять разработанную Вами инструкцию по запуску

![image](https://user-images.githubusercontent.com/59327373/208645004-eced7551-9960-4f7e-891d-d25f66c325b1.png)
